### ISSUE TITLE
A pre-compile version would be very useful

### ISSUE THREAD

**Issue by aimalkhan** [Metamogul/UTM-Snapshot-Manager#6]
Providing it as a precompiled iOS artifact will make it more accessible.
Are there any plans to do that?

**Comment by Metamogul** [comment]
Hey, thanks for the input and your interest in the app! At the moment, this is just a proof of concept and I don't own a paid Apple Developer subscription needed to produce signed binaries that can be distributed. I also think this app doesn't make so much sense as a standalone MacOS application; I just did choose that format because this made it much easier to explore the idea without diving too deep into UTM itself. Therefore I close this post. If you would like to see this as a feature of UTM, back then I did open a [feature proposal discussion where you can express your support](https://github.com/utmapp/UTM/discussions/5087).
